// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Yakumo-zi/web-terminal/ent/assetgroup"
	"github.com/Yakumo-zi/web-terminal/ent/assetgroupattribute"
	"github.com/Yakumo-zi/web-terminal/ent/predicate"
	"github.com/google/uuid"
)

// AssetGroupAttributeQuery is the builder for querying AssetGroupAttribute entities.
type AssetGroupAttributeQuery struct {
	config
	ctx        *QueryContext
	order      []assetgroupattribute.OrderOption
	inters     []Interceptor
	predicates []predicate.AssetGroupAttribute
	withGroup  *AssetGroupQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AssetGroupAttributeQuery builder.
func (agaq *AssetGroupAttributeQuery) Where(ps ...predicate.AssetGroupAttribute) *AssetGroupAttributeQuery {
	agaq.predicates = append(agaq.predicates, ps...)
	return agaq
}

// Limit the number of records to be returned by this query.
func (agaq *AssetGroupAttributeQuery) Limit(limit int) *AssetGroupAttributeQuery {
	agaq.ctx.Limit = &limit
	return agaq
}

// Offset to start from.
func (agaq *AssetGroupAttributeQuery) Offset(offset int) *AssetGroupAttributeQuery {
	agaq.ctx.Offset = &offset
	return agaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (agaq *AssetGroupAttributeQuery) Unique(unique bool) *AssetGroupAttributeQuery {
	agaq.ctx.Unique = &unique
	return agaq
}

// Order specifies how the records should be ordered.
func (agaq *AssetGroupAttributeQuery) Order(o ...assetgroupattribute.OrderOption) *AssetGroupAttributeQuery {
	agaq.order = append(agaq.order, o...)
	return agaq
}

// QueryGroup chains the current query on the "group" edge.
func (agaq *AssetGroupAttributeQuery) QueryGroup() *AssetGroupQuery {
	query := (&AssetGroupClient{config: agaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := agaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := agaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(assetgroupattribute.Table, assetgroupattribute.FieldID, selector),
			sqlgraph.To(assetgroup.Table, assetgroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, assetgroupattribute.GroupTable, assetgroupattribute.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(agaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AssetGroupAttribute entity from the query.
// Returns a *NotFoundError when no AssetGroupAttribute was found.
func (agaq *AssetGroupAttributeQuery) First(ctx context.Context) (*AssetGroupAttribute, error) {
	nodes, err := agaq.Limit(1).All(setContextOp(ctx, agaq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{assetgroupattribute.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (agaq *AssetGroupAttributeQuery) FirstX(ctx context.Context) *AssetGroupAttribute {
	node, err := agaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AssetGroupAttribute ID from the query.
// Returns a *NotFoundError when no AssetGroupAttribute ID was found.
func (agaq *AssetGroupAttributeQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = agaq.Limit(1).IDs(setContextOp(ctx, agaq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{assetgroupattribute.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (agaq *AssetGroupAttributeQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := agaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AssetGroupAttribute entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AssetGroupAttribute entity is found.
// Returns a *NotFoundError when no AssetGroupAttribute entities are found.
func (agaq *AssetGroupAttributeQuery) Only(ctx context.Context) (*AssetGroupAttribute, error) {
	nodes, err := agaq.Limit(2).All(setContextOp(ctx, agaq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{assetgroupattribute.Label}
	default:
		return nil, &NotSingularError{assetgroupattribute.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (agaq *AssetGroupAttributeQuery) OnlyX(ctx context.Context) *AssetGroupAttribute {
	node, err := agaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AssetGroupAttribute ID in the query.
// Returns a *NotSingularError when more than one AssetGroupAttribute ID is found.
// Returns a *NotFoundError when no entities are found.
func (agaq *AssetGroupAttributeQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = agaq.Limit(2).IDs(setContextOp(ctx, agaq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{assetgroupattribute.Label}
	default:
		err = &NotSingularError{assetgroupattribute.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (agaq *AssetGroupAttributeQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := agaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AssetGroupAttributes.
func (agaq *AssetGroupAttributeQuery) All(ctx context.Context) ([]*AssetGroupAttribute, error) {
	ctx = setContextOp(ctx, agaq.ctx, ent.OpQueryAll)
	if err := agaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AssetGroupAttribute, *AssetGroupAttributeQuery]()
	return withInterceptors[[]*AssetGroupAttribute](ctx, agaq, qr, agaq.inters)
}

// AllX is like All, but panics if an error occurs.
func (agaq *AssetGroupAttributeQuery) AllX(ctx context.Context) []*AssetGroupAttribute {
	nodes, err := agaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AssetGroupAttribute IDs.
func (agaq *AssetGroupAttributeQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if agaq.ctx.Unique == nil && agaq.path != nil {
		agaq.Unique(true)
	}
	ctx = setContextOp(ctx, agaq.ctx, ent.OpQueryIDs)
	if err = agaq.Select(assetgroupattribute.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (agaq *AssetGroupAttributeQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := agaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (agaq *AssetGroupAttributeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, agaq.ctx, ent.OpQueryCount)
	if err := agaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, agaq, querierCount[*AssetGroupAttributeQuery](), agaq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (agaq *AssetGroupAttributeQuery) CountX(ctx context.Context) int {
	count, err := agaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (agaq *AssetGroupAttributeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, agaq.ctx, ent.OpQueryExist)
	switch _, err := agaq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (agaq *AssetGroupAttributeQuery) ExistX(ctx context.Context) bool {
	exist, err := agaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AssetGroupAttributeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (agaq *AssetGroupAttributeQuery) Clone() *AssetGroupAttributeQuery {
	if agaq == nil {
		return nil
	}
	return &AssetGroupAttributeQuery{
		config:     agaq.config,
		ctx:        agaq.ctx.Clone(),
		order:      append([]assetgroupattribute.OrderOption{}, agaq.order...),
		inters:     append([]Interceptor{}, agaq.inters...),
		predicates: append([]predicate.AssetGroupAttribute{}, agaq.predicates...),
		withGroup:  agaq.withGroup.Clone(),
		// clone intermediate query.
		sql:  agaq.sql.Clone(),
		path: agaq.path,
	}
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (agaq *AssetGroupAttributeQuery) WithGroup(opts ...func(*AssetGroupQuery)) *AssetGroupAttributeQuery {
	query := (&AssetGroupClient{config: agaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	agaq.withGroup = query
	return agaq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AssetGroupAttribute.Query().
//		GroupBy(assetgroupattribute.FieldKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (agaq *AssetGroupAttributeQuery) GroupBy(field string, fields ...string) *AssetGroupAttributeGroupBy {
	agaq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AssetGroupAttributeGroupBy{build: agaq}
	grbuild.flds = &agaq.ctx.Fields
	grbuild.label = assetgroupattribute.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//	}
//
//	client.AssetGroupAttribute.Query().
//		Select(assetgroupattribute.FieldKey).
//		Scan(ctx, &v)
func (agaq *AssetGroupAttributeQuery) Select(fields ...string) *AssetGroupAttributeSelect {
	agaq.ctx.Fields = append(agaq.ctx.Fields, fields...)
	sbuild := &AssetGroupAttributeSelect{AssetGroupAttributeQuery: agaq}
	sbuild.label = assetgroupattribute.Label
	sbuild.flds, sbuild.scan = &agaq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AssetGroupAttributeSelect configured with the given aggregations.
func (agaq *AssetGroupAttributeQuery) Aggregate(fns ...AggregateFunc) *AssetGroupAttributeSelect {
	return agaq.Select().Aggregate(fns...)
}

func (agaq *AssetGroupAttributeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range agaq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, agaq); err != nil {
				return err
			}
		}
	}
	for _, f := range agaq.ctx.Fields {
		if !assetgroupattribute.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if agaq.path != nil {
		prev, err := agaq.path(ctx)
		if err != nil {
			return err
		}
		agaq.sql = prev
	}
	return nil
}

func (agaq *AssetGroupAttributeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AssetGroupAttribute, error) {
	var (
		nodes       = []*AssetGroupAttribute{}
		withFKs     = agaq.withFKs
		_spec       = agaq.querySpec()
		loadedTypes = [1]bool{
			agaq.withGroup != nil,
		}
	)
	if agaq.withGroup != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, assetgroupattribute.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AssetGroupAttribute).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AssetGroupAttribute{config: agaq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, agaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := agaq.withGroup; query != nil {
		if err := agaq.loadGroup(ctx, query, nodes, nil,
			func(n *AssetGroupAttribute, e *AssetGroup) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (agaq *AssetGroupAttributeQuery) loadGroup(ctx context.Context, query *AssetGroupQuery, nodes []*AssetGroupAttribute, init func(*AssetGroupAttribute), assign func(*AssetGroupAttribute, *AssetGroup)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AssetGroupAttribute)
	for i := range nodes {
		if nodes[i].asset_group_attrs == nil {
			continue
		}
		fk := *nodes[i].asset_group_attrs
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(assetgroup.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "asset_group_attrs" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (agaq *AssetGroupAttributeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := agaq.querySpec()
	_spec.Node.Columns = agaq.ctx.Fields
	if len(agaq.ctx.Fields) > 0 {
		_spec.Unique = agaq.ctx.Unique != nil && *agaq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, agaq.driver, _spec)
}

func (agaq *AssetGroupAttributeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(assetgroupattribute.Table, assetgroupattribute.Columns, sqlgraph.NewFieldSpec(assetgroupattribute.FieldID, field.TypeUUID))
	_spec.From = agaq.sql
	if unique := agaq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if agaq.path != nil {
		_spec.Unique = true
	}
	if fields := agaq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assetgroupattribute.FieldID)
		for i := range fields {
			if fields[i] != assetgroupattribute.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := agaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := agaq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := agaq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := agaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (agaq *AssetGroupAttributeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(agaq.driver.Dialect())
	t1 := builder.Table(assetgroupattribute.Table)
	columns := agaq.ctx.Fields
	if len(columns) == 0 {
		columns = assetgroupattribute.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if agaq.sql != nil {
		selector = agaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if agaq.ctx.Unique != nil && *agaq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range agaq.predicates {
		p(selector)
	}
	for _, p := range agaq.order {
		p(selector)
	}
	if offset := agaq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := agaq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AssetGroupAttributeGroupBy is the group-by builder for AssetGroupAttribute entities.
type AssetGroupAttributeGroupBy struct {
	selector
	build *AssetGroupAttributeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (agagb *AssetGroupAttributeGroupBy) Aggregate(fns ...AggregateFunc) *AssetGroupAttributeGroupBy {
	agagb.fns = append(agagb.fns, fns...)
	return agagb
}

// Scan applies the selector query and scans the result into the given value.
func (agagb *AssetGroupAttributeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, agagb.build.ctx, ent.OpQueryGroupBy)
	if err := agagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssetGroupAttributeQuery, *AssetGroupAttributeGroupBy](ctx, agagb.build, agagb, agagb.build.inters, v)
}

func (agagb *AssetGroupAttributeGroupBy) sqlScan(ctx context.Context, root *AssetGroupAttributeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(agagb.fns))
	for _, fn := range agagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*agagb.flds)+len(agagb.fns))
		for _, f := range *agagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*agagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := agagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AssetGroupAttributeSelect is the builder for selecting fields of AssetGroupAttribute entities.
type AssetGroupAttributeSelect struct {
	*AssetGroupAttributeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (agas *AssetGroupAttributeSelect) Aggregate(fns ...AggregateFunc) *AssetGroupAttributeSelect {
	agas.fns = append(agas.fns, fns...)
	return agas
}

// Scan applies the selector query and scans the result into the given value.
func (agas *AssetGroupAttributeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, agas.ctx, ent.OpQuerySelect)
	if err := agas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssetGroupAttributeQuery, *AssetGroupAttributeSelect](ctx, agas.AssetGroupAttributeQuery, agas, agas.inters, v)
}

func (agas *AssetGroupAttributeSelect) sqlScan(ctx context.Context, root *AssetGroupAttributeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(agas.fns))
	for _, fn := range agas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*agas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := agas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
