// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Yakumo-zi/web-terminal/ent/asset"
	"github.com/Yakumo-zi/web-terminal/ent/assetgroup"
	"github.com/Yakumo-zi/web-terminal/ent/assetgroupattribute"
	"github.com/Yakumo-zi/web-terminal/ent/predicate"
	"github.com/google/uuid"
)

// AssetGroupQuery is the builder for querying AssetGroup entities.
type AssetGroupQuery struct {
	config
	ctx        *QueryContext
	order      []assetgroup.OrderOption
	inters     []Interceptor
	predicates []predicate.AssetGroup
	withAssets *AssetQuery
	withAttrs  *AssetGroupAttributeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AssetGroupQuery builder.
func (agq *AssetGroupQuery) Where(ps ...predicate.AssetGroup) *AssetGroupQuery {
	agq.predicates = append(agq.predicates, ps...)
	return agq
}

// Limit the number of records to be returned by this query.
func (agq *AssetGroupQuery) Limit(limit int) *AssetGroupQuery {
	agq.ctx.Limit = &limit
	return agq
}

// Offset to start from.
func (agq *AssetGroupQuery) Offset(offset int) *AssetGroupQuery {
	agq.ctx.Offset = &offset
	return agq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (agq *AssetGroupQuery) Unique(unique bool) *AssetGroupQuery {
	agq.ctx.Unique = &unique
	return agq
}

// Order specifies how the records should be ordered.
func (agq *AssetGroupQuery) Order(o ...assetgroup.OrderOption) *AssetGroupQuery {
	agq.order = append(agq.order, o...)
	return agq
}

// QueryAssets chains the current query on the "assets" edge.
func (agq *AssetGroupQuery) QueryAssets() *AssetQuery {
	query := (&AssetClient{config: agq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := agq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := agq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(assetgroup.Table, assetgroup.FieldID, selector),
			sqlgraph.To(asset.Table, asset.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, assetgroup.AssetsTable, assetgroup.AssetsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(agq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAttrs chains the current query on the "attrs" edge.
func (agq *AssetGroupQuery) QueryAttrs() *AssetGroupAttributeQuery {
	query := (&AssetGroupAttributeClient{config: agq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := agq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := agq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(assetgroup.Table, assetgroup.FieldID, selector),
			sqlgraph.To(assetgroupattribute.Table, assetgroupattribute.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, assetgroup.AttrsTable, assetgroup.AttrsColumn),
		)
		fromU = sqlgraph.SetNeighbors(agq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AssetGroup entity from the query.
// Returns a *NotFoundError when no AssetGroup was found.
func (agq *AssetGroupQuery) First(ctx context.Context) (*AssetGroup, error) {
	nodes, err := agq.Limit(1).All(setContextOp(ctx, agq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{assetgroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (agq *AssetGroupQuery) FirstX(ctx context.Context) *AssetGroup {
	node, err := agq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AssetGroup ID from the query.
// Returns a *NotFoundError when no AssetGroup ID was found.
func (agq *AssetGroupQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = agq.Limit(1).IDs(setContextOp(ctx, agq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{assetgroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (agq *AssetGroupQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := agq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AssetGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AssetGroup entity is found.
// Returns a *NotFoundError when no AssetGroup entities are found.
func (agq *AssetGroupQuery) Only(ctx context.Context) (*AssetGroup, error) {
	nodes, err := agq.Limit(2).All(setContextOp(ctx, agq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{assetgroup.Label}
	default:
		return nil, &NotSingularError{assetgroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (agq *AssetGroupQuery) OnlyX(ctx context.Context) *AssetGroup {
	node, err := agq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AssetGroup ID in the query.
// Returns a *NotSingularError when more than one AssetGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (agq *AssetGroupQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = agq.Limit(2).IDs(setContextOp(ctx, agq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{assetgroup.Label}
	default:
		err = &NotSingularError{assetgroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (agq *AssetGroupQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := agq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AssetGroups.
func (agq *AssetGroupQuery) All(ctx context.Context) ([]*AssetGroup, error) {
	ctx = setContextOp(ctx, agq.ctx, ent.OpQueryAll)
	if err := agq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AssetGroup, *AssetGroupQuery]()
	return withInterceptors[[]*AssetGroup](ctx, agq, qr, agq.inters)
}

// AllX is like All, but panics if an error occurs.
func (agq *AssetGroupQuery) AllX(ctx context.Context) []*AssetGroup {
	nodes, err := agq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AssetGroup IDs.
func (agq *AssetGroupQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if agq.ctx.Unique == nil && agq.path != nil {
		agq.Unique(true)
	}
	ctx = setContextOp(ctx, agq.ctx, ent.OpQueryIDs)
	if err = agq.Select(assetgroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (agq *AssetGroupQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := agq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (agq *AssetGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, agq.ctx, ent.OpQueryCount)
	if err := agq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, agq, querierCount[*AssetGroupQuery](), agq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (agq *AssetGroupQuery) CountX(ctx context.Context) int {
	count, err := agq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (agq *AssetGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, agq.ctx, ent.OpQueryExist)
	switch _, err := agq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (agq *AssetGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := agq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AssetGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (agq *AssetGroupQuery) Clone() *AssetGroupQuery {
	if agq == nil {
		return nil
	}
	return &AssetGroupQuery{
		config:     agq.config,
		ctx:        agq.ctx.Clone(),
		order:      append([]assetgroup.OrderOption{}, agq.order...),
		inters:     append([]Interceptor{}, agq.inters...),
		predicates: append([]predicate.AssetGroup{}, agq.predicates...),
		withAssets: agq.withAssets.Clone(),
		withAttrs:  agq.withAttrs.Clone(),
		// clone intermediate query.
		sql:  agq.sql.Clone(),
		path: agq.path,
	}
}

// WithAssets tells the query-builder to eager-load the nodes that are connected to
// the "assets" edge. The optional arguments are used to configure the query builder of the edge.
func (agq *AssetGroupQuery) WithAssets(opts ...func(*AssetQuery)) *AssetGroupQuery {
	query := (&AssetClient{config: agq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	agq.withAssets = query
	return agq
}

// WithAttrs tells the query-builder to eager-load the nodes that are connected to
// the "attrs" edge. The optional arguments are used to configure the query builder of the edge.
func (agq *AssetGroupQuery) WithAttrs(opts ...func(*AssetGroupAttributeQuery)) *AssetGroupQuery {
	query := (&AssetGroupAttributeClient{config: agq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	agq.withAttrs = query
	return agq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AssetGroup.Query().
//		GroupBy(assetgroup.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (agq *AssetGroupQuery) GroupBy(field string, fields ...string) *AssetGroupGroupBy {
	agq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AssetGroupGroupBy{build: agq}
	grbuild.flds = &agq.ctx.Fields
	grbuild.label = assetgroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.AssetGroup.Query().
//		Select(assetgroup.FieldName).
//		Scan(ctx, &v)
func (agq *AssetGroupQuery) Select(fields ...string) *AssetGroupSelect {
	agq.ctx.Fields = append(agq.ctx.Fields, fields...)
	sbuild := &AssetGroupSelect{AssetGroupQuery: agq}
	sbuild.label = assetgroup.Label
	sbuild.flds, sbuild.scan = &agq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AssetGroupSelect configured with the given aggregations.
func (agq *AssetGroupQuery) Aggregate(fns ...AggregateFunc) *AssetGroupSelect {
	return agq.Select().Aggregate(fns...)
}

func (agq *AssetGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range agq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, agq); err != nil {
				return err
			}
		}
	}
	for _, f := range agq.ctx.Fields {
		if !assetgroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if agq.path != nil {
		prev, err := agq.path(ctx)
		if err != nil {
			return err
		}
		agq.sql = prev
	}
	return nil
}

func (agq *AssetGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AssetGroup, error) {
	var (
		nodes       = []*AssetGroup{}
		_spec       = agq.querySpec()
		loadedTypes = [2]bool{
			agq.withAssets != nil,
			agq.withAttrs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AssetGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AssetGroup{config: agq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, agq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := agq.withAssets; query != nil {
		if err := agq.loadAssets(ctx, query, nodes,
			func(n *AssetGroup) { n.Edges.Assets = []*Asset{} },
			func(n *AssetGroup, e *Asset) { n.Edges.Assets = append(n.Edges.Assets, e) }); err != nil {
			return nil, err
		}
	}
	if query := agq.withAttrs; query != nil {
		if err := agq.loadAttrs(ctx, query, nodes,
			func(n *AssetGroup) { n.Edges.Attrs = []*AssetGroupAttribute{} },
			func(n *AssetGroup, e *AssetGroupAttribute) { n.Edges.Attrs = append(n.Edges.Attrs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (agq *AssetGroupQuery) loadAssets(ctx context.Context, query *AssetQuery, nodes []*AssetGroup, init func(*AssetGroup), assign func(*AssetGroup, *Asset)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*AssetGroup)
	nids := make(map[uuid.UUID]map[*AssetGroup]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(assetgroup.AssetsTable)
		s.Join(joinT).On(s.C(asset.FieldID), joinT.C(assetgroup.AssetsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(assetgroup.AssetsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(assetgroup.AssetsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*AssetGroup]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Asset](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "assets" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (agq *AssetGroupQuery) loadAttrs(ctx context.Context, query *AssetGroupAttributeQuery, nodes []*AssetGroup, init func(*AssetGroup), assign func(*AssetGroup, *AssetGroupAttribute)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*AssetGroup)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.AssetGroupAttribute(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(assetgroup.AttrsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.asset_group_attrs
		if fk == nil {
			return fmt.Errorf(`foreign-key "asset_group_attrs" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "asset_group_attrs" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (agq *AssetGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := agq.querySpec()
	_spec.Node.Columns = agq.ctx.Fields
	if len(agq.ctx.Fields) > 0 {
		_spec.Unique = agq.ctx.Unique != nil && *agq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, agq.driver, _spec)
}

func (agq *AssetGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(assetgroup.Table, assetgroup.Columns, sqlgraph.NewFieldSpec(assetgroup.FieldID, field.TypeUUID))
	_spec.From = agq.sql
	if unique := agq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if agq.path != nil {
		_spec.Unique = true
	}
	if fields := agq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assetgroup.FieldID)
		for i := range fields {
			if fields[i] != assetgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := agq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := agq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := agq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := agq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (agq *AssetGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(agq.driver.Dialect())
	t1 := builder.Table(assetgroup.Table)
	columns := agq.ctx.Fields
	if len(columns) == 0 {
		columns = assetgroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if agq.sql != nil {
		selector = agq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if agq.ctx.Unique != nil && *agq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range agq.predicates {
		p(selector)
	}
	for _, p := range agq.order {
		p(selector)
	}
	if offset := agq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := agq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AssetGroupGroupBy is the group-by builder for AssetGroup entities.
type AssetGroupGroupBy struct {
	selector
	build *AssetGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aggb *AssetGroupGroupBy) Aggregate(fns ...AggregateFunc) *AssetGroupGroupBy {
	aggb.fns = append(aggb.fns, fns...)
	return aggb
}

// Scan applies the selector query and scans the result into the given value.
func (aggb *AssetGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aggb.build.ctx, ent.OpQueryGroupBy)
	if err := aggb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssetGroupQuery, *AssetGroupGroupBy](ctx, aggb.build, aggb, aggb.build.inters, v)
}

func (aggb *AssetGroupGroupBy) sqlScan(ctx context.Context, root *AssetGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(aggb.fns))
	for _, fn := range aggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*aggb.flds)+len(aggb.fns))
		for _, f := range *aggb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*aggb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aggb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AssetGroupSelect is the builder for selecting fields of AssetGroup entities.
type AssetGroupSelect struct {
	*AssetGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ags *AssetGroupSelect) Aggregate(fns ...AggregateFunc) *AssetGroupSelect {
	ags.fns = append(ags.fns, fns...)
	return ags
}

// Scan applies the selector query and scans the result into the given value.
func (ags *AssetGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ags.ctx, ent.OpQuerySelect)
	if err := ags.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssetGroupQuery, *AssetGroupSelect](ctx, ags.AssetGroupQuery, ags, ags.inters, v)
}

func (ags *AssetGroupSelect) sqlScan(ctx context.Context, root *AssetGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ags.fns))
	for _, fn := range ags.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ags.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ags.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
