// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Asset is the predicate function for asset builders.
type Asset func(*sql.Selector)

// AssetGroup is the predicate function for assetgroup builders.
type AssetGroup func(*sql.Selector)

// AssetGroupAttribute is the predicate function for assetgroupattribute builders.
type AssetGroupAttribute func(*sql.Selector)

// Credential is the predicate function for credential builders.
type Credential func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)
